### ISSUE TITLE
Исходный код не хранится в ветках

### ISSUE THREAD

**Issue by 1nfameArts** [TrueS1gma/DevelWare#1]
Pull Requestы и проблемы репортить будет почти не возможно.
Простой ответ.

**Comment by DevelWareIDE** [comment]
Я тебя понял. Это будет сделано при релизе 16.7.1.

**Comment by 1nfameArts** [comment]
Pull request inbound, я уже делаю форк для имплементации заранее

**Comment by 1nfameArts** [comment]
Решено в недавном патче
